### ISSUE TITLE
Markdown Formating Error

### ISSUE THREAD

**Issue by tupio** [tupio/ktu-notification-bot#5]
**Describe the bug**
Some KTU Notification contains special characters such as "(",  ")". This interferes with the Markdown syntax of the Message and forms malformed messages like shown in the channel.

**To Reproduce**
1. Run the bot in debug mode

**Expected behavior**
The special characters should be escaped properly.

**Additional context**
Due to some unknown reason, this bug even shows random behavior.

**Comment by AJAYK-01** [comment]
try parsing through html instead of markdown, it works for me 
i made one too, (as a separate project, hadn't seen this one at that time)
